export const constants = {
  CLUSTER_NAME: 'pufferpanel',
  SERVICE_NAME: 'pufferpanel-server',
  MC_SERVER_CONTAINER_NAME: 'pufferpanel-server',
  WATCHDOG_SERVER_CONTAINER_NAME: 'minecraft-ecsfargate-watchdog',
  DOMAIN_STACK_REGION: 'us-east-1',
  ECS_VOLUME_NAME: 'data',
  ECS_CONFIG_VOLUME_NAME: 'config',
  ECS_SERVERS_VOLUME_NAME: 'servers',
  ECS_EMAILS_VOLUME_NAME: 'emails',
  SSM_PARAM_PREFIX: '/minecraft-ondemand/',
  HOSTED_ZONE_SSM_PARAMETER: 'MinecraftHostedZoneID',
  LAUNCHER_LAMBDA_ARN_SSM_PARAMETER: 'LauncherLambdaRoleArn',
  ALEXA_LAUNCHER_LAMBDA_ARN_SSM_PARAMETER: 'AlexaLauncherLambdaRoleArn',
  JAVA_EDITION_DOCKER_IMAGE: 'itzg/minecraft-server',
  BEDROCK_EDITION_DOCKER_IMAGE: 'itzg/minecraft-bedrock-server',
  PUFFER_PANEL_DOCKER_IMAGE: 'pufferpanel/pufferpanel:devel',
}
